version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_username
      MONGO_INITDB_ROOT_PASSWORD: root_password
    ports:
      - "27017:27017"
  
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: your_database_name
    links:
      - mongodb
